Repository codex-storage/nim-codex, pull requests merged in 2024-12, with the labels that each got.

#1017 Run release tests for docker images
  .github/workflows/docker-dist-tests.yml
  .github/workflows/docker-reusable.yml
Labels: E:Distributed Client Testing

#1016 Send pluralized wantBlock messages
  codex/blockexchange/engine/engine.nim
  codex/logutils.nim
Labels: Client

#922 Validator historical state restoration
  .github/workflows/ci.yml
  build.nims
  codex/contracts.nim
  codex/contracts/market.nim
  codex/contracts/provider.nim
  codex/market.nim
  codex/validation.nim
  tests/codex/helpers/mockmarket.nim
  tests/codex/testvalidation.nim
  tests/contracts/helpers/mockprovider.nim
  tests/contracts/testMarket.nim
  tests/contracts/testProvider.nim
  tests/integration/codexconfig.nim
  tests/integration/marketplacesuite.nim
  tests/integration/multinodes.nim
  tests/integration/nodeprocess.nim
  tests/integration/testmarketplace.nim
  tests/integration/testvalidator.nim
  tests/testContracts.nim
  tests/testIntegration.nim
Labels: Marketplace
