Repository codex-storage/nim-codex, pull requests merged in 2024-10, with the labels that each got.

#930 Remove moved docs
  README.md
  docs/DownloadFlow.md
  docs/TwoClientTest.md
Labels: documentation

#939 Use Ubuntu 20.04 for Linux amd64 releases
  .github/workflows/release.yml
Labels: bug

#935 Remove moved docs
  docs/Marketplace.md
Labels: documentation

#944 Update Codex Testnet marketplace contract address
  codex/contracts/deployment.nim
Labels: E:Testnet Setup

#942 fix(restapi): Add cors headers when the request is returning errors
  codex/rest/api.nim
Labels: Client

#955 Download API upgrade
  codex/rest/api.nim
  openapi.yaml
  tests/integration/codexclient.nim
  tests/integration/testblockexpiration.nim
  tests/integration/testupdownload.nim
Labels: Client, API
